"""Add company_dev Association Table

Revision ID: 360be7ed2778
Revises: 51b9f3a7c085
Create Date: 2025-05-24 18:40:16.113511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360be7ed2778'
down_revision = '51b9f3a7c085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_dev',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_dev_company_id_companies')),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_company_dev_dev_id_devs')),
    sa.PrimaryKeyConstraint('company_id', 'dev_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_dev')
    # ### end Alembic commands ###
